/**
 * <primer-geometry-problem name="…"> — the interactive "apply-the-theorem" construction sandbox.
 *
 * A problem is GENERATED by the theorem engine (src/geometry-engine/*): it picks a scaffold, gates the
 * theorem pool by the page's prerequisite DAG, and synthesises a fresh figure with some angles GIVEN
 * and others BLANK, plus an ordered solution chain. The learner fills the blanks (typed angle values),
 * optionally using the construction tools (auxiliary lines, parallel / equal-length / right-angle
 * marks) to reason, then hits **Check** — which walks the engine's chain, ticking each blank and, at
 * the first wrong one, revealing that step's theorem hint. **Refresh** rolls a brand-new problem.
 *
 *   <primer-geometry-problem name="angleChase"></primer-geometry-problem>
 *   <script type="module">
 *     import { registerGeometryProblem } from "primer";
 *     registerGeometryProblem("angleChase", { generate: { scaffolds: ["parallelTransversal"], maxSteps: 4 } });
 *   </script>
 *
 * The board is built INTERACTIVE (src/components/jsxgraph-board.ts `interactive`), so points drag and tools
 * click. Embedded in a `<primer-quiz>` (a `{ problem: "name" }` question) it exposes a `solved` getter
 * and fires `primer:problem-graded` so the quiz folds it into the scorecard.
 * @module
 */

import { attachShared, awaitRegistration } from "./shared.ts";
import { getGeometryProblem } from "../scenes.ts";
import type { GeometryProblemConfig } from "../scenes.ts";
import { themeColors } from "../theme.ts";
import { t } from "../i18n.ts";
import { adoptJsxCss, disposeBoard, wrapBoard, resolveJXG } from "./jsxgraph-board.ts";
import { makeGeometryTools } from "../geometry-tools.ts";
import { makeRng } from "../rng.ts";
import { checkAnswer } from "../quiz-vars.ts";
import { loadMathLive } from "../mathfield.ts";
import { getMathKeyboard } from "../math-keyboards.ts";
import { SCAFFOLDS, anglePos } from "../geometry-engine/scaffolds.ts";
import { generateProblem } from "../geometry-engine/generate.ts";
import type { Problem } from "../geometry-engine/generate.ts";
import type { DerivStep } from "../geometry-engine/chain.ts";
import { RULES } from "../geometry-engine/rules.ts";
import { buildAdjacency, allowedTheorems } from "../geometry-engine/learned.ts";

/** Cached `dist/graph.json` adjacency (fetched once across all instances). */
let graphPromise: Promise<Map<string, string[]> | null> | null = null;
function loadGraph(): Promise<Map<string, string[]> | null> {
  if (!graphPromise) {
    graphPromise = fetch("/dist/graph.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((g) => buildAdjacency(g))
      .catch(() => null);
  }
  return graphPromise;
}

/** Infer the current page's concept id from `/concepts/<id>` (legacy `.html` accepted). */
function pageConceptId() {
  const m = (typeof location !== "undefined" ? location.pathname : "").match(/\/concepts\/(.+?)(?:\.html?)?$/);
  return m ? m[1] : "";
}

/** Built-in English step justifications, keyed by rule. The engine emits `rule` + the produced value. */
const JUSTIFY: Record<string, (v: number) => string> = {
  vertical: (v) => `Vertical angles are equal, so this angle is ${v}°.`,
  linearPair: (v) => `Angles on a straight line add to 180°, so this angle is ${v}°.`,
  corresponding: (v) => `Corresponding angles (parallel lines) are equal, so this angle is ${v}°.`,
  alternateInterior: (v) => `Alternate interior angles (the “Z”) are equal, so this angle is ${v}°.`,
  coInterior: (v) => `Co-interior angles (parallel lines) add to 180°, so this angle is ${v}°.`,
  triangleSum: (v) => `The angles of a triangle add to 180°, so this angle is ${v}°.`,
  isoscelesBase: (v) => `Base angles of an isosceles triangle are equal, so this angle is ${v}°.`,
  exteriorAngle: (v) => `The exterior angle equals the two remote interior angles, so this angle is ${v}°.`,
  anglesAtPoint: (v) => `Angles around a point add to 360°, so this angle is ${v}°.`,
};

export class PrimerGeometryProblem extends HTMLElement {
  #board: any = null;
  /** Raw JSXGraph namespace (for Coords + freeBoard). */ #jsx: any = null;
  #problem: Problem | null = null;
  /** fillable angle key → its `<math-field>` (or fallback `<input>`). */ #inputs: Map<string, any> = new Map();
  /** Every non-given quantity the learner can fill. */ #fillable: Array<{ key: string; value: number; pos: [number, number]; isTarget: boolean; kind: "angle" | "length" }> = [];
  /** Whether MathLive loaded (else fall back to plain text boxes). */ #mathlive: boolean = false;
  /** chain step keyed by produced angle, for hints. */ #hintByKey: Map<string, DerivStep> = new Map();
  /** A theorem explanation for EVERY fillable angle (chain step if on the path, else any determining relation). */ #explainByKey: Map<string, { rule: string | null; value: number }> = new Map();
  /** Per-blank explanation text for AUTHORED problems. */ #hintText: Map<string, string> = new Map();
  /** The goal sentence (authored problems set their own). */ #goal: string = "";
  /** Numbered step badges shown on solve. */ #badges: Array<{ el: HTMLElement; pos: [number, number] }> = [];
  /** Marking-tool group state. */ #marks: { parallel: { pending: any; count: number }; equal: { pending: any; count: number } } = { parallel: { pending: null, count: 0 }, equal: { pending: null, count: 0 } };
  #onTheme: (() => void) | null = null;
  #stopWaiting: (() => void) | null = null;
  #buildGen: number = 0;
  #seed: number | null = null;
  #solved: boolean = false;
  /** Current construction tool. */ #tool: string = "answer";
  /** Construction tools the toolbar offers (besides the always-present Fill in / Undo). */ #toolset: string[] = ["line", "parallel", "equal", "right"];
  /** Learner-created elements (for undo/reset). */ #added: any[] = [];
  /** Pickable points for the tools. */ #picks: { x: number; y: number; el: any }[] = [];
  /** First point chosen by the line tool. */ #pendingPoint: any = null;
  #resizeObs: ResizeObserver | null = null;

  /** Whether this problem has been solved (for the embedding quiz). */
  get solved(): boolean {
    return this.#solved;
  }

  connectedCallback() {
    const root = this.shadowRoot ?? attachShared(this);
    adoptJsxCss(root, () => this.isConnected);
    root.innerHTML = this.#shellHtml();
    // The action buttons are part of the static shell — wire them ONCE here (not per build, which
    // would stack duplicate listeners every Refresh).
    root.querySelector(".check")?.addEventListener("click", () => this.check());
    root.querySelector(".refresh")?.addEventListener("click", () => this.refresh());
    root.querySelector(".reset")?.addEventListener("click", () => this.reset());
    this.#onTheme = () => void this.#build(root);
    document.addEventListener("theme-change", this.#onTheme);
    void this.#build(root);
  }

  disconnectedCallback() {
    if (this.#onTheme) document.removeEventListener("theme-change", this.#onTheme);
    this.#onTheme = null;
    this.#stopWaiting?.();
    this.#stopWaiting = null; // clear so a reconnect can re-arm the registration wait (guarded by truthiness)
    this.#dispose();
  }

  get #root() {
    return this.shadowRoot as ShadowRoot;
  }

  /** The element shell (styles + layout). */
  #shellHtml() {
    return `
      <style>
        .prob { display: block; }
        .goal { font-family: var(--primer-font-display, sans-serif); font-weight: 700;
          color: var(--primer-ink, #111); margin: 0 0 0.5rem; text-align: center; }
        /* The toolbar is a single control bar above the diagram: construction tools (when any) plus the
           always-present Check / Refresh / Restart actions. */
        .toolbar { display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center; justify-content: center;
          margin-bottom: 0; padding: 0.4rem; border-radius: 0.5rem 0.5rem 0 0;
          background: var(--primer-control-bg, #f1ede4); border: 1px solid var(--primer-control-border, #ccc);
          border-bottom: none; font-family: var(--primer-font-ui, sans-serif); }
        .tools { display: contents; } /* tool buttons flow inline beside the action buttons */
        .toolbar button { padding: 0.25rem 0.6rem; border-radius: 0.35rem; font-size: 0.85rem;
          border: 1px solid var(--primer-control-border, #ccc);
          background: var(--primer-control-bg, #fff); color: var(--primer-ink, #111); }
        .toolbar button[aria-pressed="true"] { background: var(--primer-accent, #4d5bd1);
          color: var(--primer-accent-ink, #fff); border-color: transparent; }
        /* Check is the primary action; a touch of space sets the actions off from the tools. */
        .toolbar .check { margin-left: 0.4rem; font-weight: 700; color: var(--primer-accent-ink, #fff);
          background: var(--primer-accent, #4d5bd1); border-color: transparent; }
        /* Embedded in a quiz, the quiz's "Check answers" grades it and the question is fixed — hide our
           own Check + Refresh (Restart stays, to clear an attempt). */
        :host([embedded]) .check, :host([embedded]) .refresh { display: none; }
        .stage { position: relative; width: 100%; aspect-ratio: 7 / 4; overflow: hidden;
          background: var(--primer-viz-bg, #fff); border-radius: var(--primer-radius, 0.6rem);
          box-shadow: inset 0 0 0 1px var(--primer-border, #e6e0d4); touch-action: none; }
        /* The toolbar sits directly above; square the stage's top corners so they meet flush. */
        .toolbar + .stage { border-top-left-radius: 0; border-top-right-radius: 0; }
        /* The JSXGraph board gets its OWN container (sharing the stage with the overlay breaks
           JSXGraph's resize measurement). */
        .board { position: absolute; inset: 0; }
        .stage svg { display: block; width: 100% !important; height: 100% !important; }
        .overlay { position: absolute; inset: 0; pointer-events: none; z-index: 2; }
        /* Fillable boxes: the diagram backdrop (--primer-viz-bg) equals --primer-surface in every
           theme, so a "surface" fill would vanish. Use the recessed control surface (distinct from the
           backdrop) plus a soft lift so each box reads clearly against the figure — but stays quieter
           than a full answer box. */
        .overlay input, .overlay math-field.mf {
          position: absolute; transform: translate(-50%, -50%); width: 1.85rem;
          text-align: center; font-size: 0.72rem; line-height: 1;
          font-family: var(--primer-font-ui, ui-sans-serif, system-ui, sans-serif);
          border-radius: 0.25rem; border: 1px solid var(--primer-border, #ccc);
          /* 30%-opaque fill so the figure shows through; opaque fallback for engines without color-mix. */
          background: var(--primer-control-bg, #f1ede4);
          background: color-mix(in srgb, var(--primer-control-bg, #f1ede4) 30%, transparent);
          color: var(--primer-ink, #111); pointer-events: auto; }
        .overlay input { padding: 0 0.1rem; }
        /* MathLive box: keep it compact, sans-serif glyphs, and hide the in-field menu / keyboard
           toggles (the module keyboard pops up on focus instead). */
        .overlay math-field.mf { padding: 0; min-height: 0.95rem; --smart-fence-opacity: 0;
          font-family: var(--primer-font-ui, ui-sans-serif, system-ui, sans-serif); }
        .overlay math-field.mf::part(menu-toggle),
        .overlay math-field.mf::part(virtual-keyboard-toggle) { display: none; }
        /* The target (the chase's answer) is the prominent one: the brighter surface + accent ring. */
        .overlay input.target, .overlay math-field.mf.target {
          background: var(--primer-surface, #fff);
          background: color-mix(in srgb, var(--primer-surface, #fff) 30%, transparent);
          border-color: var(--primer-accent, #4d5bd1); box-shadow: 0 0 0 2px var(--primer-ring, rgba(70,90,230,0.55)); }
        .overlay input.right, .overlay math-field.mf.right { border-color: var(--primer-ok, #1a8f3c); color: var(--primer-ok, #1a8f3c);
          background: var(--primer-ok-bg, #e6f6ec);
          background: color-mix(in srgb, var(--primer-ok-bg, #e6f6ec) 30%, transparent); }
        .overlay input.wrong, .overlay math-field.mf.wrong { border-color: var(--primer-bad, #c0392b); color: var(--primer-bad, #c0392b);
          background: var(--primer-bad-bg, #fdecea);
          background: color-mix(in srgb, var(--primer-bad-bg, #fdecea) 30%, transparent); }
        /* A small numbered badge marking which solution step an angle belongs to (shown on solve). */
        .overlay .step-badge { position: absolute; transform: translate(-50%, -50%);
          display: grid; place-items: center; min-width: 1rem; height: 1rem; padding: 0 0.18rem;
          border-radius: 1rem; font-size: 0.6rem; font-weight: 700; line-height: 1; color: #fff;
          box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.25); pointer-events: none; }
        .feedback { margin: 0.55rem 0 0; min-height: 1.2rem; font-size: 0.95rem; }
        .feedback .ok { color: var(--primer-ok, #1a8f3c); font-weight: 700; }
        .feedback .bad { color: var(--primer-bad, #c0392b); font-weight: 700; }
        .feedback ol { margin: 0.4rem 0 0; padding-left: 1.2rem; }
        /* The solution chain, each step colour-matched to its angle on the figure. */
        .feedback ol.chain { list-style: none; padding-left: 0; }
        .feedback ol.chain li { display: flex; align-items: flex-start; gap: 0.45rem; margin: 0.25rem 0; }
        .feedback ol.chain .step-n { flex: none; display: grid; place-items: center; min-width: 1.2rem;
          height: 1.2rem; border-radius: 1rem; color: #fff; font-size: 0.72rem; font-weight: 700; }
        .meta { color: var(--primer-ink-soft, #667); }
      </style>
      <div class="prob">
        <p class="goal"></p>
        <div class="toolbar" part="toolbar">
          <span class="tools"></span>
          <button class="check" type="button">${t("quiz.check")}</button>
          <button class="refresh" type="button">${t("geometry.refresh")}</button>
          <button class="reset" type="button">${this.#str("restart", "Restart")}</button>
        </div>
        <div class="stage" part="stage"><div class="board"></div><div class="overlay"></div></div>
        <p class="feedback" role="status" aria-live="polite"></p>
      </div>`;
  }

  /**
   * (Re)build the problem: resolve config, gate the theorem pool, generate, draw, wire.
   */
  async #build(root: ShadowRoot) {
    const stage = root.querySelector(".stage") as HTMLElement;
    const name = this.getAttribute("name") ?? this.getAttribute("scene") ?? "";
    const config = getGeometryProblem(name);
    if (!config) {
      this.#awaitRegistration(root, name);
      return;
    }
    this.#stopWaiting?.();
    this.#tool = "answer";
    if (this.#seed === null) this.#seed = (Math.random() * 0x100000000) >>> 0;
    const gen = ++this.#buildGen;
    this.#dispose();
    const overlay = stage.querySelector(".overlay") as HTMLElement;
    overlay.replaceChildren();
    this.#inputs.clear();
    this.#fillable = [];
    this.#hintByKey = new Map();
    this.#explainByKey = new Map();
    this.#hintText = new Map();
    this.#badges = [];
    this.#marks = { parallel: { pending: null, count: 0 }, equal: { pending: null, count: 0 } };
    this.#added = [];
    this.#picks = [];
    this.#pendingPoint = null;
    this.#solved = false;
    this.#problem = null;
    this.#goal = "";
    this.#feedback("");

    try {
      const mod = await import("jsxgraph");
      if (!this.isConnected || gen !== this.#buildGen) return;
      const JXG = resolveJXG(mod);
      this.#jsx = JXG;
      const rng = makeRng(this.#seed as number);

      // Two sources: an AUTHORED figure (the author draws it + declares the fill-in blanks), or an
      // engine-GENERATED angle chase. Both end up with the same #fillable boxes + grading.
      const ok = (config as any).authored
        ? this.#buildAuthored(stage, JXG, (config as any).authored, rng)
        : await this.#buildGenerated(stage, JXG, config, rng, gen);
      if (!ok || gen !== this.#buildGen) return;

      this.#renderToolbar();
      this.#renderGoal();
      // Load MathLive now (cached) so the figure + toolbar are already on screen; the editable boxes
      // appear a moment later on first load, instantly thereafter.
      this.#mathlive = await loadMathLive();
      if (gen !== this.#buildGen) return;
      this.#placeFields(overlay);
      this.#syncOverlay();
    } catch (err) {
      const error = err instanceof Error ? err.message : String(err);
      this.#feedback(`<span class="meta">${t("manim.runError", { error })}</span>`);
    }
  }

  /** Engine path: gate the theorem pool, generate an angle chase, set up the fillable angles + hints,
   * draw the figure. Returns false (with a message) if nothing is derivable. */
  async #buildGenerated(stage: HTMLElement, JXG: any, config: any, rng: any, gen: number) {
    this.#toolset = config.generate.tools ?? ["line", "parallel", "equal", "right"];
    const allowed = await this.#allowedPool(config, JXG);
    if (gen !== this.#buildGen) return false;
    const scaffoldNames = config.generate.scaffolds.filter((n: string) => SCAFFOLDS[n as keyof typeof SCAFFOLDS]);
    const scaffoldName = rng.pick(scaffoldNames.length ? scaffoldNames : ["parallelTransversal"]);
    const figure = SCAFFOLDS[scaffoldName as keyof typeof SCAFFOLDS](rng);
    const problem = generateProblem(figure, allowed, rng, {
      minSteps: config.generate.minSteps ?? 2,
      maxSteps: config.generate.maxSteps ?? 4,
    });
    this.#problem = problem;
    if (!problem) {
      stage.querySelector(".overlay")?.replaceChildren();
      this.#feedback(`<span class="meta">${this.#str("noTheorems", "No relevant theorems learned yet — come back after the lessons above.")}</span>`);
      return false;
    }
    // EVERY non-given angle is fillable — that's how you chase the solution. The engine's chain only
    // supplies the ordered HINTS and which one is the final target.
    const givenKeys = new Set(problem.givens.map((g: any) => g.key));
    this.#fillable = figure.angles
      .filter((a: any) => !givenKeys.has(a.key))
      .map((a: any) => ({ key: a.key, value: a.value, pos: anglePos(figure, a), isTarget: a.key === problem.target, kind: "angle" as const }));
    this.#hintByKey = new Map(problem.blanks.map((b: any) => [b.key, b]));
    this.#explainByKey = new Map();
    for (const f of this.#fillable) {
      const step = this.#hintByKey.get(f.key);
      if (step) { this.#explainByKey.set(f.key, { rule: step.rule, value: step.value }); continue; }
      const reln = figure.relations.find(
        (r: any) => allowed.has(r.conceptId) && r.terms.some((t: any) => t.key === f.key),
      );
      this.#explainByKey.set(f.key, { rule: reln ? reln.rule : null, value: f.value });
    }
    this.#drawBoardFigure(stage, JXG, figure, problem);
    return true;
  }

  /** Authored path: the author's `build(toolkit)` draws the figure and returns `{ blanks, goal }`; the
   * blanks become the on-figure fill-in boxes (angles → geometry-angles keyboard, lengths →
   * geometry-lengths). The figure is static — the overlay boxes are the only interaction. */
  #buildAuthored(stage: HTMLElement, JXG: any, authored: any, rng: any) {
    this.#toolset = authored.tools ?? [];
    const { board, tools, colors } = this.#initBoard(stage, JXG, authored.boundingbox ?? [-5, 5, 5, -5]);
    const spec = authored.build({ board, JXG, colors, rng, ...tools }) ?? {};
    for (const el of board.objectsList) el.setAttribute?.({ fixed: true, highlight: false }); // static figure
    board.update();
    const blanks = spec.blanks ?? [];
    this.#fillable = blanks.map((b: any, i: number) => ({
      key: `b${i}`, value: b.answer, pos: b.pos, isTarget: b.target ?? i === 0, kind: b.kind ?? "angle",
    }));
    this.#hintText = new Map(blanks.map((b: any, i: number) => [`b${i}`, b.hint ?? ""]));
    this.#goal = spec.goal ?? "";
    return true;
  }

  /** Resolve the allowed theorem pool: explicit override, else DAG-gated, else (offline) all rules. */
  async #allowedPool(config: GeometryProblemConfig, _JXG: any) {
    const gen = config.generate ?? { scaffolds: [] };
    const allRuleConcepts = new Set(Object.values(RULES).map((r) => r.conceptId));
    if (gen.theorems) return new Set(gen.theorems);
    const adj = await loadGraph();
    if (!adj) return allRuleConcepts; // offline / no graph → don't block, allow everything
    const id = gen.pageId ?? pageConceptId();
    if (!id || !adj.has(id)) return allRuleConcepts;
    return allowedTheorems(adj, id, allRuleConcepts);
  }

  /** Create a fresh interactive JSXGraph board for the figure, and keep the overlay boxes glued to it
   * as it updates/resizes. Returns the board + the drawing tools + the resolved palette. */
  #initBoard(stage: HTMLElement, JXG: any, boundingbox: [number, number, number, number]) {
    const colors = themeColors();
    // Recreate a FRESH board container each build. Re-initialising JSXGraph on the same element across
    // a Refresh is fragile (the element keeps its old JSXGraph container id / leftover state); a brand
    // new div sidesteps all of it.
    stage.querySelector(".board")?.remove();
    const boardEl = document.createElement("div");
    boardEl.className = "board";
    stage.insertBefore(boardEl, stage.querySelector(".overlay"));
    let board = null;
    const wrapped = wrapBoard(JXG, colors, (b: any) => { board = b; }, { interactive: true });
    board = wrapped.JSXGraph.initBoard(boardEl, { boundingbox, keepaspectratio: true, axis: false, grid: false });
    board.options.line.point1 = { ...board.options.line.point1, visible: false, withLabel: false };
    board.options.line.point2 = { ...board.options.line.point2, visible: false, withLabel: false };
    this.#board = board;
    // Keep the overlay boxes glued to their anchors as the board updates (drags) or the stage resizes.
    if (typeof board.on === "function") board.on("update", () => this.#syncOverlay());
    if (typeof ResizeObserver !== "undefined") {
      this.#resizeObs?.disconnect();
      this.#resizeObs = new ResizeObserver(() => this.#syncOverlay());
      this.#resizeObs.observe(stage);
    }
    return { board, tools: makeGeometryTools(board, colors), colors };
  }

  /** Draw an engine FIGURE (edges, parallel marks, given/blank angle marks) and wire construction tools. */
  #drawBoardFigure(stage: HTMLElement, JXG: any, figure: any, problem: any) {
    const { board, tools, colors } = this.#initBoard(stage, JXG, figure.boundingbox);

    // Edges.
    for (const [p, q] of figure.edges) {
      board.create("segment", [figure.points[p], figure.points[q]], {
        strokeColor: colors.line, strokeWidth: 2, fixed: true, highlight: false,
      });
    }
    // GIVEN parallel marks: the "these lines are parallel" chevrons the chase relies on. Each parallel
    // group gets its own number of chevrons (1, 2, …) so distinct groups are distinguishable.
    (figure.parallels ?? []).forEach((group: number[], gi: number) => {
      for (const ei of group) {
        const [p, q] = figure.edges[ei];
        const a = figure.points[p];
        const b = figure.points[q];
        tools.parallelMark((a[0] + b[0]) / 2, (a[1] + b[1]) / 2, {
          along: [b[0] - a[0], b[1] - a[1]], count: gi + 1, color: colors.line,
        });
      }
    });
    // Pickable vertex points (small, faint) for the construction tools.
    this.#picks = [];
    for (const [, coord] of Object.entries(figure.points)) {
      const c = coord as [number, number];
      const pt = board.create("point", c, { name: "", size: 1, strokeColor: colors.line, fillColor: colors.line, fixed: true, withLabel: false, highlight: false });
      this.#picks.push({ x: c[0], y: c[1], el: pt });
    }

    const givenKeys = new Set(problem.givens.map((g: any) => g.key));
    for (const ang of figure.angles) {
      const V = figure.points[ang.vertex];
      const P1 = figure.points[ang.from];
      const P2 = figure.points[ang.to];
      if (givenKeys.has(ang.key)) {
        // A given: a clear arc + its value, in small ink text.
        tools.angleMark(V, P1, P2, { label: `${ang.value}°`, color: colors.ink, radius: 0.5, fontSize: 12 });
      } else {
        // A fillable angle: a faint arc to anchor its input box (the target a touch stronger).
        tools.angleMark(V, P1, P2, { color: ang.key === problem.target ? colors.cat[0] : colors.line, radius: 0.5 });
      }
    }
    board.update();
    this.#wireBoardTools(board);
  }

  /** Render the construction tool buttons into the toolbar's `.tools` slot (beside the static Check /
   * Refresh / Restart actions). Empty when the problem offers no construction tools. */
  #renderToolbar() {
    const toolsEl = this.#root.querySelector(".tools") as HTMLElement;
    toolsEl.replaceChildren();
    if (!this.#toolset.length) return; // no construction tools → just the action buttons
    const labels: Record<string, string> = {
      answer: this.#str("toolAnswer", "Fill in"),
      line: this.#str("toolLine", "Draw line"),
      parallel: this.#str("toolParallel", "Mark ∥"),
      equal: this.#str("toolEqual", "Mark ="),
      right: this.#str("toolRight", "Right ∟"),
      undo: this.#str("toolUndo", "Undo"),
    };
    // "Fill in" is always first and "Undo" always last; in between, only the configured tools.
    const keys = ["answer", ...this.#toolset.filter((k) => k in labels && k !== "answer" && k !== "undo"), "undo"];
    for (const key of keys) {
      const b = document.createElement("button");
      b.type = "button";
      b.textContent = labels[key];
      b.dataset.tool = key;
      if (key === this.#tool) b.setAttribute("aria-pressed", "true");
      b.addEventListener("click", () => {
        if (key === "undo") return this.#undo();
        this.#tool = key;
        this.#pendingPoint = null;
        for (const el of toolsEl.querySelectorAll("button")) el.removeAttribute("aria-pressed");
        b.setAttribute("aria-pressed", "true");
      });
      toolsEl.append(b);
    }
  }

  /** Show the goal sentence — an authored problem's own goal, else the default angle-chase prompt. */
  #renderGoal() {
    const goal = this.#root.querySelector(".goal") as HTMLElement;
    goal.textContent = this.#goal || this.#str("goal", "Chase the angles: fill in any you can work out, ending with the highlighted one.");
  }

  /** Overlay a small editor at EVERY fillable quantity's position — a MathLive `<math-field>` (its
   * module keyboard is `geometry-angles` for angles, `geometry-lengths` for lengths), or a plain text
   * box if MathLive isn't available. */
  #placeFields(overlay: HTMLElement) {
    overlay.replaceChildren();
    this.#inputs.clear();
    const haveMf = this.#mathlive && typeof customElements !== "undefined" && !!customElements.get("math-field");
    for (const f of this.#fillable) {
      const kb = f.kind === "length" ? "geometry-lengths" : "geometry-angles";
      const el = haveMf ? this.#makeField(f, kb) : this.#makeInput(f);
      overlay.append(el);
      this.#inputs.set(f.key, el);
    }
  }

  /** A MathLive editor for one fillable quantity, wired to pop its module keyboard on focus. */
  #makeField(f: any, kb: string) {
    const mf = document.createElement("math-field") as any;
    mf.mathVirtualKeyboardPolicy = "manual"; // we show on focus / hide on blur
    mf.className = `mf${f.isTarget ? " target" : ""}`;
    mf.setAttribute("aria-label", this.#str("blankLabel", "unknown angle", { noun: this.#noun() }));
    mf.dataset.key = f.key;
    const layout = getMathKeyboard(kb);
    mf.addEventListener("input", () => mf.classList.remove("right", "wrong"));
    mf.addEventListener("focusin", () => {
      // Render typed content in the sans-serif MATH variant (CSS can't reach MathLive's glyph font).
      // Applied while the cursor is collapsed so the next inserted digits inherit it.
      try { mf.applyStyle?.({ variant: "sans-serif" }); } catch { /* not mounted yet */ }
      const vk = (globalThis as any).mathVirtualKeyboard;
      if (!vk) return;
      if (layout) vk.layouts = [layout];
      vk.editToolbar = "none";
      vk.show();
    });
    mf.addEventListener("focusout", () => { (globalThis as any).mathVirtualKeyboard?.hide(); });
    return mf;
  }

  /** A plain text box fallback (MathLive failed to load). */
  #makeInput(f: any) {
    const input = document.createElement("input");
    input.type = "text";
    input.inputMode = "numeric";
    input.autocomplete = "off";
    input.className = f.isTarget ? "target" : "";
    input.setAttribute("aria-label", this.#str("blankLabel", "unknown angle", { noun: this.#noun() }));
    input.dataset.key = f.key;
    input.addEventListener("input", () => { input.classList.remove("right", "wrong"); });
    return input;
  }

  /** Roll a brand-new problem (a fresh seed) and rebuild. */
  refresh() {
    this.#seed = (Math.random() * 0x100000000) >>> 0;
    void this.#build(this.#root);
  }

  /* ----------------------------- grading ----------------------------- */

  /**
   * Grade every angle the learner filled against its true value. The problem is solved when the
   * highlighted TARGET is filled and correct and nothing filled is wrong. On a wrong entry, the first
   * one's theorem hint is shown (from the engine's chain where it applies, else a generic nudge); if the
   * target is still blank, the learner is pointed at it.
   */
  check() {
    if (!this.#fillable.length) return false;
    this.#clearSolutionMarks();
    /** every wrong angle the learner filled */
    const wrong: Array<{ key: string; label: string }> = [];
    let targetOk = false;
    let targetFilled = false;
    for (const f of this.#fillable) {
      const input = this.#inputs.get(f.key);
      if (!input) continue;
      const raw = this.#fieldValue(input);
      const filled = raw.trim() !== "";
      const ok = filled && checkAnswer(f.value, raw);
      input.classList.toggle("right", filled && ok);
      input.classList.toggle("wrong", filled && !ok);
      if (filled && !ok) wrong.push({ key: f.key, label: this.#explainText(f.key) });
      if (f.isTarget) { targetFilled = filled; targetOk = ok; }
    }
    this.#solved = targetOk && wrong.length === 0;
    if (this.#solved) {
      // Colour each solution step and ring its quantity; the numbered list maps onto the figure.
      const items = this.#solutionItems();
      this.#markAngles(items, true);
      this.#feedback(`<span class="ok">✓ ${this.#str("solved", "Solved! Every step checks out.")}</span>` + this.#explainHtml(items));
    } else if (wrong.length) {
      // Explain EVERY wrong angle, badge each one, and colour-match the explanations.
      this.#markAngles(wrong, false);
      this.#feedback(`<span class="bad">✗ ${this.#str("notYet", "Not yet —")}</span> ${this.#str("review", "these angles need another look:", { noun: this.#noun() })}` + this.#explainHtml(wrong));
    } else if (!targetFilled) {
      this.#feedback(`<span class="bad">${this.#str("fillTarget", "Fill in the highlighted angle to finish.", { noun: this.#noun() })}</span>`);
    }
    this.dispatchEvent(new CustomEvent("primer:problem-graded", { bubbles: true, detail: { solved: this.#solved } }));
    return this.#solved;
  }

  /** The ordered, labelled solution steps to colour-code on solve: the engine's chain for a generated
   * problem, else each authored blank with its hint. */
  #solutionItems(): Array<{ key: string; label: string }> {
    if (this.#problem) {
      return this.#problem.blanks.map((b: any) => ({ key: b.key, label: JUSTIFY[b.rule](b.value) }));
    }
    return this.#fillable.map((f) => ({ key: f.key, label: this.#explainText(f.key) || `${f.value}` }));
  }

  /** Read a box's value as a plain string for grading — unwrapping MathLive's font-variant macros
   * (e.g. `\mathsf{70}` → `70`) so the sans-serif rendering doesn't reach the grader. */
  #fieldValue(el: any) {
    const v = typeof el?.value === "string" ? el.value : "";
    // Drop MathLive's font-variant wrappers (the sans-serif rendering) robustly, even when nested
    // around a degree marker: e.g. "\mathsf{70^{\circ}}" / "\mathsf{70}^{\circ}" → "70^\circ", which
    // checkAnswer then reduces to 70. (Numeric/short answers, so removing braces is safe.)
    return v
      .replace(/\\math(?:sf|rm|it|bf|tt|cal|bb|frak)\b/g, "")
      .replace(/[{}]/g, "")
      .trim();
  }

  /** The explanation for a quantity: an authored per-blank hint, else its theorem (chain step on the
   * path, else any determining relation), else a generic nudge. */
  #explainText(key: string) {
    const authored = this.#hintText.get(key);
    if (authored) return authored;
    const e = this.#explainByKey.get(key);
    if (e && e.rule && JUSTIFY[e.rule]) return JUSTIFY[e.rule](e.value);
    return this.#str("genericHint", "That angle isn't right yet — look at angles on a line, vertical angles, or the parallel-line rules.");
  }

  /** The colour from the sequence palette for solution step `i`. */
  #stepColor(i: number) {
    const cat = themeColors().cat;
    return cat[i % cat.length];
  }

  /** A colour-coded numbered list (used for the solution chain AND the wrong-angle explanations). */
  #explainHtml(items: Array<{ key: string; label: string }>) {
    const lis = items
      .map((it, i) => `<li><span class="step-n" style="background:${this.#stepColor(i)}">${i + 1}</span><span>${it.label}</span></li>`)
      .join("");
    return `<ol class="chain">${lis}</ol>`;
  }

  /** Badge each listed angle with its sequence-coloured number (matching {@link #explainHtml}); when
   * `ring`, also outline the box in that colour (used for the all-correct solution path). */
  #markAngles(items: Array<{ key: string; label: string }>, ring: boolean) {
    const overlay = this.#root.querySelector(".overlay") as HTMLElement;
    items.forEach((it, i) => {
      const c = this.#stepColor(i);
      if (ring) {
        const input = this.#inputs.get(it.key);
        if (input) { input.style.borderColor = c; input.style.boxShadow = `0 0 0 2px ${c}`; }
      }
      const f = this.#fillable.find((x) => x.key === it.key);
      if (!f) return;
      const badge = document.createElement("span");
      badge.className = "step-badge";
      badge.textContent = String(i + 1);
      badge.style.background = c;
      overlay.append(badge);
      this.#badges.push({ el: badge, pos: f.pos });
    });
    this.#syncOverlay();
  }

  /** Remove the solution badges and clear the per-step inline ring on the boxes. */
  #clearSolutionMarks() {
    for (const { el } of this.#badges) el.remove();
    this.#badges = [];
    for (const input of this.#inputs.values()) { input.style.borderColor = ""; input.style.boxShadow = ""; }
  }

  /** Reset: clear inputs, learner-drawn marks, and feedback (same problem). */
  reset() {
    this.#clearSolutionMarks();
    for (const input of this.#inputs.values()) { input.value = ""; input.classList.remove("right", "wrong"); }
    this.#undo(true);
    this.#marks = { parallel: { pending: null, count: 0 }, equal: { pending: null, count: 0 } };
    this.#solved = false;
    this.#feedback("");
  }

  /* -------------------------- construction --------------------------- */

  /** Wire pointer-driven construction tools onto the interactive board. */
  #wireBoardTools(board: any) {
    if (typeof board.on !== "function") return;
    board.on("down", (evt: any) => {
      try {
        const [x, y] = board.getUsrCoordsOfMouse(evt);
        if (this.#tool === "line") this.#toolLine(board, x, y);
        else if (this.#tool === "parallel") this.#toolEdgeMark(board, x, y, "parallel");
        else if (this.#tool === "equal") this.#toolEdgeMark(board, x, y, "equal");
        else if (this.#tool === "right") this.#toolRight(board, x, y);
      } catch {
        /* a stray click off the figure is harmless */
      }
    });
  }

  /** Nearest pickable point to (x,y) within a tolerance, or null. */
  #nearestPick(x: number, y: number) {
    let best = null;
    let bd = 0.5; // user-unit tolerance
    for (const p of this.#picks) {
      const d = Math.hypot(p.x - x, p.y - y);
      if (d < bd) { bd = d; best = p; }
    }
    return best;
  }

  /** Line tool: click two points to draw a dashed auxiliary line. */
  #toolLine(board: any, x: number, y: number) {
    const colors = themeColors();
    let pick = this.#nearestPick(x, y);
    if (!pick) {
      // No existing point near the click — drop a free draggable point there.
      const pt = board.create("point", [x, y], { name: "", size: 2, strokeColor: colors.cat[1], fillColor: colors.cat[1], withLabel: false });
      this.#added.push(pt);
      pick = { x, y, el: pt };
      this.#picks.push(pick);
    }
    if (!this.#pendingPoint) { this.#pendingPoint = pick; return; }
    if (this.#pendingPoint !== pick) {
      const line = board.create("line", [this.#pendingPoint.el, pick.el], {
        straightFirst: false, straightLast: true, strokeColor: colors.cat[1], strokeWidth: 1.5, dash: 2, fixed: true, highlight: false,
      });
      this.#added.push(line);
    }
    this.#pendingPoint = null;
    board.update();
  }

  /**
   * Parallel / equal-length marking, in PAIRS: click one edge (it's remembered), then a second edge —
   * both get the SAME mark. Each successive pair uses one more tick/chevron (1, 2, 3…) so distinct
   * groups read apart. Clicking the same edge twice cancels the pending selection.
   */
  #toolEdgeMark(board: any, x: number, y: number, kind: "parallel" | "equal") {
    const fig = this.#problem?.figure;
    if (!fig) return;
    let bestIdx = -1;
    let bd = 0.4;
    fig.edges.forEach((e: [string, string], i: number) => {
      const d = distToSeg(x, y, fig.points[e[0]], fig.points[e[1]]);
      if (d < bd) { bd = d; bestIdx = i; }
    });
    if (bestIdx < 0) return;
    const grp = this.#marks[kind];
    if (grp.pending === null) { grp.pending = bestIdx; return; } // first of the pair — wait for the second
    if (grp.pending === bestIdx) { grp.pending = null; return; } // same edge → cancel
    const n = grp.count + 1; // this pair's tick count
    grp.count = n;
    for (const idx of [grp.pending, bestIdx]) this.#markEdge(board, fig, idx, kind, n);
    grp.pending = null;
    board.update();
  }

  /** Draw `n` parallel chevrons / equal-length ticks on edge `idx`. */
  #markEdge(board: any, fig: any, idx: number, kind: "parallel" | "equal", n: number) {
    const colors = themeColors();
    const tools = makeGeometryTools(board, colors);
    const [p, q] = fig.edges[idx];
    const a = fig.points[p];
    const b = fig.points[q];
    const els = kind === "parallel"
      ? tools.parallelMark((a[0] + b[0]) / 2, (a[1] + b[1]) / 2, { along: [b[0] - a[0], b[1] - a[1]], count: n, color: colors.cat[2] })
      : tools.tickMark(a, b, { count: n, color: colors.cat[2] });
    for (const e of els) this.#added.push(e);
  }

  /** Right-angle mark at the nearest vertex with two incident edges. */
  #toolRight(board: any, x: number, y: number) {
    const fig = this.#problem?.figure;
    if (!fig) return;
    const pick = this.#nearestPick(x, y);
    if (!pick) return;
    // Find the vertex name nearest the pick, and two edges incident to it.
    let vname = null;
    for (const [pname, c] of Object.entries(fig.points)) {
      const cc = c as [number, number];
      if (Math.hypot(cc[0] - pick.x, cc[1] - pick.y) < 1e-6) { vname = pname; break; }
    }
    if (!vname) return;
    const inc = fig.edges.filter((e: [string, string]) => e[0] === vname || e[1] === vname);
    if (inc.length < 2) return;
    const other = (e: [string, string]) => (e[0] === vname ? e[1] : e[0]);
    const colors = themeColors();
    const el = makeGeometryTools(board, colors).rightAngle(fig.points[vname], fig.points[other(inc[0])], fig.points[other(inc[1])], { color: colors.cat[2] });
    this.#added.push(el);
    board.update();
  }

  /** Undo the last learner-created element (or all of them when `all`). */
  #undo(all = false) {
    if (!this.#board) return;
    const drop = all ? this.#added.splice(0) : this.#added.splice(-1);
    for (const el of drop) { try { this.#board.removeObject(el); } catch { /* already gone */ } }
    this.#pendingPoint = null;
    this.#marks.parallel.pending = null;
    this.#marks.equal.pending = null;
    this.#board.update();
  }

  /* ------------------------------ overlay ----------------------------- */

  /**
   * Position each blank input over its angle, converting user coords → board pixels using only
   * guaranteed board properties (origin + unitX/unitY, which already encode the keep-aspect scaling).
   * Wrapped so a transient bad state (board mid-rebuild) can never throw out of an event handler.
   */
  #syncOverlay() {
    try {
      const board = this.#board;
      if (!board || !board.origin) return;
      const ox = board.origin.scrCoords[1];
      const oy = board.origin.scrCoords[2];
      const ux = board.unitX;
      const uy = board.unitY;
      const byKey = new Map(this.#fillable.map((f) => [f.key, f]));
      for (const [key, input] of this.#inputs) {
        const f = byKey.get(key);
        if (!f) continue;
        input.style.left = `${ox + f.pos[0] * ux}px`;
        input.style.top = `${oy - f.pos[1] * uy}px`;
      }
      // Step badges sit just up-and-left of their box.
      for (const { el, pos } of this.#badges) {
        el.style.left = `${ox + pos[0] * ux - 15}px`;
        el.style.top = `${oy - pos[1] * uy - 12}px`;
      }
    } catch {
      /* board mid-rebuild / freed — skip this frame */
    }
  }

  #awaitRegistration(root: ShadowRoot, name: string) {
    if (this.#stopWaiting) return;
    this.#stopWaiting = awaitRegistration("primer:geometry-problem-registered", name, {
      onReady: () => {
        this.#stopWaiting?.();
        this.#stopWaiting = null;
        void this.#build(root);
      },
    });
  }

  /** A localized chrome string for the problem element — global i18n (`geometryProblem.*`), which
   * falls back to English then the key, so it never logs a "missing scene string" error. (The second
   * argument is the inline English default kept at the call sites for readability; `t` supplies it.) */
  #str(key: string, _fallback?: string, vars?: Record<string, string | number>) {
    return t(`geometryProblem.${key}`, vars);
  }

  /** The noun for the quantity being filled, for feedback wording: "side" (lengths), "angle", or a
   * neutral "value" for a mix. */
  #noun(): string {
    const kinds = new Set(this.#fillable.map((f) => f.kind));
    if (kinds.size === 1) return kinds.has("length") ? "side" : "angle";
    return "value";
  }

  #feedback(html: string) {
    const fb = this.#root?.querySelector(".feedback");
    if (fb) fb.innerHTML = html;
  }

  #dispose() {
    this.#resizeObs?.disconnect();
    this.#resizeObs = null;
    disposeBoard(this.#jsx?.JSXGraph, this.#board);
    this.#board = null;
  }
}

if (!customElements.get("primer-geometry-problem")) {
  customElements.define("primer-geometry-problem", PrimerGeometryProblem);
}

/** Distance from point (px,py) to segment a–b (all in user coords). */
function distToSeg(px: number, py: number, a: number[], b: number[]) {
  const vx = b[0] - a[0];
  const vy = b[1] - a[1];
  const wx = px - a[0];
  const wy = py - a[1];
  const len2 = vx * vx + vy * vy || 1;
  let t = (wx * vx + wy * vy) / len2;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (a[0] + t * vx), py - (a[1] + t * vy));
}

// Reposition overlay inputs when the board updates (drag/resize) — registered once per element via a
// shared rAF tick would be heavier; instead each board.update() is cheap, so the element re-syncs on a
// window resize and after construction actions (which call board.update()). A lightweight observer:
